### ISSUE TITLE
카린 봇 명령어 인식 오류

### ISSUE THREAD

**Issue by ruda328** [KaRinKaRin876/KRB-v2#1]
## 카린봇의 버그를 실행시키는 사진을 올려주세요!
![캡처](https://user-images.githubusercontent.com/62368624/82035735-e6f3dd80-96da-11ea-80fe-2f211ab4b2e3.PNG)

## 카린봇의 버그를 해결한 뒤의 동작을 써주세요!
명령어로 인식되지 않아야 합니다.

## 혹시 해당 버그로 인하여 문제가 된 것이 있으신가요?
기존 채팅에서 봇이 예상치 않게 반응합니다.

## 유저의 커넥션 정보
Windows 10 64bit
Discord - 최신버전

## 이슈를 올리기 전에 아래를 확인해주세요!
- [v] 이전에 처리했거나 중복되는 이슈는 없나요?
- [v] 해당 버그를 정상적인 방법으로 발생시킬 수 있나요?
* 위의 확인 작성중에 문제되는 것이 있다면 이슈를 진행하는 속도가 느려질 수 있습니다!

**Comment by KaRinKaRin876** [comment]
Approved

**Comment by ruda328** [comment]
Upvote

**Comment by KaRinKaRin876** [comment]
해당 버그는 [ 0 . 3 . 0 ] 버전에서 수정될 예정입니다.

**Comment by KaRinKaRin876** [comment]
Fixed

**Comment by ruda328** [comment]
확인
