### ISSUE TITLE
명령어 인식 오류(정상 명령어 인식 오류) 

### ISSUE THREAD

**Issue by ruda328** [KaRinKaRin876/KRB-v2#2]
## 카린봇의 버그를 실행시키는 사진을 올려주세요!
![캡처](https://user-images.githubusercontent.com/62368624/82119256-e2e9bd80-97b7-11ea-86f1-81a484d79827.PNG)

## 카린봇의 버그를 해결한 뒤의 동작을 써주세요!
잘못 입력한 명령어로 인식되지 않아야 합니다.

## 혹시 해당 버그로 인하여 문제가 된 것이 있으신가요?
잘 입력했는데도 이상하게 인식해서 짜증납니다(?)

## 유저의 커넥션 정보
Win10 64bit

## 이슈를 올리기 전에 아래를 확인해주세요!
- [v] 이전에 처리했거나 중복되는 이슈는 없나요?
- [v] 해당 버그를 정상적인 방법으로 발생시킬 수 있나요?
* 위의 확인 작성중에 문제되는 것이 있다면 이슈를 진행하는 속도가 느려질 수 있습니다!

**Comment by KaRinKaRin876** [comment]
this bug will fix in 0.3.1 release

**Comment by KaRinKaRin876** [comment]
Fixed
만약 버그가 다시 나면 해당 명령어 사진을 올려서 다시 이슈를 생성해 주세요.
